[build-system]
requires = ["uv_build>=0.8.22"]
build-backend = "uv_build"

[project]
name = "aind-clabe"
description = "A library for a minimal framework that can be used to build experimental interfaces."
authors = [{ name = "Bruno Cruz", email = "bruno.cruz@alleninstitute.org" }]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
version = "0.11.2"
readme = { file = "README.md", content-type = "text/markdown" }

classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
]

dependencies = [
    "pydantic>=2.7",
    "pydantic-settings",
    "gitpython",
    "requests",
    "semver",
    "rich",
    "aind_behavior_services>=0.13.0",
    "textual>=8.2.7",
    "opentelemetry-api>=1.24",
]

[project.urls]
Documentation = "https://allenneuraldynamics.github.io/clabe/"
Repository = "https://github.com/AllenNeuralDynamics/clabe/"
Issues = "https://github.com/AllenNeuralDynamics/clabe/issues"
Changelog = "https://github.com/AllenNeuralDynamics/clabe/releases"

[project.optional-dependencies]
web = [
    "textual-serve",
]
otel = [
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp-proto-http",
    "opentelemetry-exporter-otlp-proto-grpc",
    "pyyaml",
]
aind-services = [
    "requests",
    "pyyaml",
    "pykeepass",
    "msal; sys_platform == 'win32'",
    "aind-data-schema>=2",
    "aind-data-transfer-service >= 1.22.0",
    "aind-watchdog-service >= 0.1.6",
]

[dependency-groups]

dev = [
    "ruff",
    "codespell",
    "coverage",
    'pytest',
    'pytest-cov',
    'pytest-asyncio',
    'interrogate',
    "aind-clabe[aind-services]",
    "aind-clabe[web]",
    "aind-clabe[otel]",
]

docs = [
    "aind-clabe[aind-services]",
    'mkdocs',
    'mkdocs-material',
    'mkdocstrings[python]',
    'pymdown-extensions',
]

[project.scripts]
clabe = "clabe.cli:main"

[tool.uv]
default-groups = ['dev']

[tool.uv.build-backend]
module-name = "clabe"

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = ["tests/assets/*"]

[tool.ruff.lint]
extend-select = ["Q", "RUF100", "C90", "I"]
extend-ignore = []
mccabe = { max-complexity = 14 }
pydocstyle = { convention = "google" }

[tool.codespell]
skip = '.git,*.pdf,*.svg,./bonsai,*.bonsai,./docs/_build,uv.lock'
ignore-words-list = "nd, assertIn"

[tool.pytest.ini_options]
addopts = "--strict-markers --tb=short --cov=src --cov-report=term-missing --ignore=tests/assets"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = ["asyncio: mark test as requiring asyncio"]

[tool.interrogate]
ignore-init-method = true
ignore-magic = true
ignore_module = true
ignore_nested_functions = true
ignore_overloaded_functions = true
ignore-private = true
fail-under = 100
exclude = [
    "__init__.py",
    "tests",
    "docs",
    "build",
    "setup.py",
    "examples",
    "site",
]
